project:
  type: website

website:
  title: "Hooked on Data"
  search: true
  navbar:
    right:
      - about.qmd
      - speaking.qmd
      - icon: github
        href: https://github.com/robinsones
      - icon: twitter
        href: https://twitter.com/robinson_es
format:
  html:
    theme: custom.scss
    css: styles.css



