---
title: "Speaking"
toc: true
toc-title: Table of contents
toc-location: left
---

I regularly give talks on A/B Testing, programming in R, data science career advice, and more. I've given talks across the country and internationally, to audiences ranging from 25 people to 800. If you're interested in having me speak at your event, please contact me at robinson.es[at]gmail.com

My co-author Jacqueline Nolis and I also have our own podcast based on our book of the same title, Build a Career in Data Science. Each episode covers one chapter of the book, sharing the main takeaways as well as our personal experiences. The podcast is available on all major podcast platforms, and you can visit the website [here](https://podcast.bestbook.cool/). 

## A/B Testing

#### 6 Guidelines for A/B Testing

March 2019, CXL Live. [Slides](https://www.slideshare.net/EmilyRobinson52/6-guidelines-for-ab-testing-145531526), [Recording](https://conversionxl.com/institute/media/guidelines-for-ab-testing/) - you will need to [sign-up here](https://conversionxl.com/institute/checkout/) for free.

#### Building an A/B Testing Analytics System

January 2019, RStudio Conference. [Slides](https://www.slideshare.net/secret/Ba52FYuH2FoWE), [Recording](https://resources.rstudio.com/rstudio-conf-2019/building-an-ab-testing-analytics-system-with-r-and-shiny). 

November 2018, DC R Conference. [Recording](https://www.youtube.com/watch?v=zDONDfXzKdA&feature=youtu.be).

October 2018, Nor'eastR Conference. 

#### 10 Guidelines for A/B Testing

June 2019, Keynote at Microsoft internal One Analyst conference in Seattle. 

November 2018, DataCamp Webinar. [Recording](https://support.datacamp.com/hc/en-us/articles/360012283593-Nov-2018-Webinar-10-Guidelines-for-A-B-Testing), [Slides](https://docs.google.com/presentation/d/19_x0RJqz10ZPCC29IVkp6mDEJiitXglSgkdM4DAKW6Q/edit). 

October 2018, [PyData NYC](https://pydata.org/nyc2018/). 

October 2018, [Taiwanese Data Professionals](https://www.meetup.com/Taiwanese-Data-Professionals/events/vdgkdqyxnbjc/).

####  A/B Testing in the Wild

October 2017, West Point Academy. [Slides](https://github.com/robinsones/AB-Testing-Slides/blob/master/AB%20Testing%20in%20the%20Wild.pdf).

September 2017, Demystifying Data Science Conference by Metis. [Recording](https://www.youtube.com/watch?v=hlYFksjjgXg), [Slides](https://www.slideshare.net/secret/DBLR67WhEK2qWd).

July 2017, New York Open Statistical Programming Meetup. [Recording](https://www.youtube.com/watch?v=SF-ryGgLOgQ), [Slides](https://github.com/robinsones/AB-Testing-Slides/blob/master/AB%20Testing%20in%20the%20Wild.pdf). 

## Programming in R and Python

#### Don't Let the Snake Bite: Integrating Python with your R Workflow

November 2022, Keynote at XII Conference of R Users, Spain. [Slides](https://rpubs.com/robinson_es/python_with_r).

#### A UseR's Introduction to Machine Learning in AWS

September 2022, SoCal R Users Group. 

October 2021, Salt Lake City R Users Group. [Slides](bit.ly/awsdogs), [Recording](https://www.youtube.com/watch?v=EZXJmFg4MIg&t=2844s). 

#### funneljoin: Defining a Tidy Grammar of Funnels in R

August 2020, NY R conference.[Recording](https://www.youtube.com/watch?v=tVbdppsEgmQ&feature=youtu.be).  

November 2019, Booking.com Headquarters.

November 2019, DC R conference. [Slides](https://speakerdeck.com/robinsones/funneljoin-defining-a-tidy-grammar-of-funnels-in-r), [Recording](https://www.youtube.com/watch?v=-n4XaYHDlG8&feature=youtu.be).

#### Everything You Wanted to Know About Making R Packages but Were Afraid to Ask

November 2019, Columbia University. 

May 2019, New York R Conference. [Recording](https://www.youtube.com/embed/33BzunEXEIE),  [Slides](https://www.slideshare.net/EmilyRobinson52/everything-you-wanted-to-know-about-making-an-r-package-but-were-afraid-to-ask).

#### The Lesser Known Stars of the Tidyverse

December 2018, DataCamp Webinar. [Recording](https://www.youtube.com/watch?v=uG3igAGX7UE&t=632s).

April 2018, New York R Conference. [Recording](https://www.youtube.com/watch?v=ax4LXQ5t38k), [Slides](https://www.slideshare.net/secret/sMVjYvcd7yh16z).

April 2018, Women in Analytics Conference, Facebook. [Slides](https://www.slideshare.net/secret/AcaLNF6VSwtkrT), [Code](https://github.com/robinsones/wia_talk/blob/master/wia_talk.Rmd). 

February 2018, RStudio Conference. [Recording](https://www.rstudio.com/resources/videos/the-lesser-known-stars-of-the-tidyverse/), [Slides](https://www.slideshare.net/EmilyRobinson52/the-lesser-known-stars-of-the-tidyverse). 

January 2018, Data Day Texas Conference. [Slides](https://github.com/robinsones/Data-Day-Talk/blob/master/Data_day_presentation.pdf), [Code](https://github.com/robinsones/Data-Day-Talk/blob/master/data_day_script_accompanying.md). 

## Data Science Career Advice

#### Which Comes First: the Model or the Stakeholder Commitment to Deploy It?

February 2023, Data Mishaps Night. 

#### Build a Career in Data Science 

April 2023, Northeastern University.

August 2020, Grace Hoppers Celebration Scholars meetup. 

June 2020, Data Umbrella, [Recording](https://www.youtube.com/watch?v=HsFFuFYz7zE) (including 45 minutes of Q&A). 

June 2020, DataScienceGO Virtual, [Recording](https://www.youtube.com/watch?v=ChCYyWl2lNY), [Slides](https://speakerdeck.com/robinsones/build-a-career-in-data-science-7ef18f3c-876d-4ece-b755-9909ad2eacda). 

November 2019, R-Ladies DC and DC Emerging Technologies, [Slides](https://speakerdeck.com/robinsones/build-a-career-in-data-science).

#### Data Science Demstifyed 

November 2019, Conversion Hotel in the Netherlands. [Slides](https://www.slideshare.net/webanalisten/ch2019-keynote-emily-robinson-data-science-demystified), [5-minute video summary](https://conversionhotel.com/session/keynote-2019-data-science-demystified/).

#### Joining the Data Science Community

July 2019, Demystifying Data Science, [Slides](https://speakerdeck.com/robinsones/joining-the-data-science-community), [Recording](https://www.youtube.com/watch?v=YiROP9-OJh4&feature=youtu.be).

May 2018, July 2018, and April 2020, Metis Data Science Bootcamp. [Slides](https://speakerdeck.com/robinsones/joining-the-data-science-community-245bca95-0556-4653-9511-9be65f3c228a).

#### Creating a Strong Data Science Portfolio

June 2019, [Data Matters](https://skillsmatter.com/meetups/11783-keynote-evening-with-emily-robinson) in London. [Recording](https://skillsmatter.com/skillscasts/13056-creating-a-strong-data-science-portfolio), [Slides](https://speakerdeck.com/robinsones/build-a-strong-data-science-portfolio).

## Podcasts

November 2022, Build a Career in Data Science on Open Data Science. [Recording](https://www.youtube.com/watch?v=57Q8v0XyOko&t=1s). 

November 2020, Building a Career in Data Science on Chai Data Science. [Recording](https://www.youtube.com/watch?v=-OSWCeo18vs&feature=youtu.be). 

October 2020, Build a Career in Data Science on The Artists of Data Science . [Recording](https://theartistsofdatascience.fireside.fm/jacqueline-nolis-emily-robinson). 

July 2020, How to Jump into Data Science from Any Background on Develomentor. [Recording](https://develomentor.com/2020/07/23/emily-robinson-jacqueline-nolis-how-to-jump-into-data-science-from-any-background-76/). 

June 2020, Build a Career in Data Science Book Session with Women in Analytics and Women in Tech International. [Recording](https://www.youtube.com/watch?v=P9rfb09FWjI).

April 2020, Build a Career in Data Science on Talk Python to Me. [Recording](https://talkpython.fm/episodes/show/262/build-a-career-in-data-science). 

April 2020, Tackling Data Science Job Hunting, Interviews & Negotiations on Super Data Science Podcast. [Recording and transcript](https://www.superdatascience.com/podcast/tackling-data-science-job-hunting-interviews-and-negotiations). 

April 2020, Data Science and Sponsorship on Greater Than Code. [Recording and episode outline](https://www.greaterthancode.com/data-science-and-sponsorship). 

April 2020, Building a Career in Data Science on Towards Data Science. [Recording and summary](https://towardsdatascience.com/building-a-career-in-data-science-with-emily-robinson-27cd9bdba4c4). 

March 2020, Start a Career in Data Science on Women in TECH with Ariana. [Recording](https://anchor.fm/womenintech/episodes/Start-a-Career-in-Data-Science-with-Emily--Jacqueline-ebcbee).

March 2020, Building a Career in Data Science on Practical AI. [Recording and transcript](https://changelog.com/practicalai/81). 

February 2018, Data Science and Online Experiments at Etsy on DataFramed. [Recording](https://soundcloud.com/dataframed/9-data-science-and-online-experiments-at-etsy). 
